{{- if and (not .Values.secret.existingSecret) .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "issue-agent.fullname" . }}-secret
  labels:
    {{- include "issue-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
