<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Octokit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../IssueAgent.Domain/IssueAgent.Domain.csproj" />
    <ProjectReference Include="../IssueAgent.Git/IssueAgent.Git.csproj" />
    <ProjectReference Include="../IssueAgent.Providers/IssueAgent.Providers.csproj" />
  </ItemGroup>
</Project>
