using System.Security.Cryptography;
using System.Text;
using LibGit2Sharp;

namespace IssueAgent.Git.Tests;

/// <summary>Exercises the real Git CLI boundary for SSH transport hook suppression and SSH host-key
/// verification (specification §§11 and 36).</summary>
public sealed class GitSshTransportTests : IDisposable
{
    private static readonly object PathLock = new();
    private readonly List<string> cleanupPaths = [];

    [Fact]
    public void PushNeverExecutesPrePushHook()
    {
        var bareRemotePath = Track(TempGitFixtures.CreateBareRemoteRepository(out _));
        var worktreePath = Track(TempGitFixtures.CreateTempDirectory());
        Directory.Delete(worktreePath);
        Repository.Clone(bareRemotePath, worktreePath);
        RunGitCli(worktreePath, "checkout", "-b", "agent/issue-1");
        RunGitCli(worktreePath, "remote", "set-url", "origin", $"git@localhost:{bareRemotePath}");

        using (var repository = new Repository(worktreePath))
        {
            File.WriteAllText(Path.Combine(worktreePath, "change.txt"), "change\n");
            Commands.Stage(repository, "change.txt");
            var signature = new Signature("Test", "test@example.com", DateTimeOffset.UtcNow);
            repository.Commit("Change", signature, signature);
        }

        var markerPath = Path.Combine(worktreePath, "pre-push-fired");
        var hookPath = Path.Combine(worktreePath, ".git", "hooks", "pre-push");
        File.WriteAllText(hookPath, $"#!/bin/sh\ntouch \"{markerPath}\"\n");
        MakeExecutable(hookPath);

        WithFakeCommand("ssh", $"#!/bin/sh\nexec git-receive-pack \"{bareRemotePath}\"\n", () =>
            GitSshTransport.Push(worktreePath, "agent/issue-1", SshAuthentication()));

        Assert.False(File.Exists(markerPath));
        using var bareRepository = new Repository(bareRemotePath);
        Assert.NotNull(bareRepository.Branches["agent/issue-1"]);
    }

    [Fact]
    public void CloneUsesConfiguredSshUsernameInsteadOfUsernameInRemoteUrl()
    {
        var bareRemotePath = Track(TempGitFixtures.CreateBareRemoteRepository(out _));
        var clonePath = Track(TempGitFixtures.CreateTempDirectory());
        Directory.Delete(clonePath);
        var sshArgumentsPath = Path.Combine(Track(TempGitFixtures.CreateTempDirectory()), "ssh-arguments");

        WithFakeCommand(
            "ssh",
            $"#!/bin/sh\nprintf '%s\\n' \"$@\" > \"{sshArgumentsPath}\"\nexec git-upload-pack \"{bareRemotePath}\"\n",
            () => GitSshTransport.CloneBare(
                $"remote-user@localhost:{bareRemotePath}",
                clonePath,
                new GitAuthentication
                {
                    Mode = GitAuthenticationMode.Ssh,
                    SshPrivateKey = "test private key",
                    SshUsername = "configured-user",
                    SshTrust = new SshTrust { Mode = SshHostVerificationMode.None },
                }));

        Assert.Contains("User=configured-user", File.ReadAllText(sshArgumentsPath), StringComparison.Ordinal);
    }

    [Fact]
    public void ScanAndVerifyHostKeysRejectsFingerprintWithDifferentBase64LetterCase()
    {
        var key = Convert.ToBase64String(Encoding.UTF8.GetBytes("test SSH host key"));
        var fingerprint = FingerprintFor(key);
        var wrongCaseFingerprint = ChangeBase64LetterCase(fingerprint);
        var keyscanLine = $"example.test ssh-ed25519 {key}";

        WithFakeCommand("ssh-keyscan", $"#!/bin/sh\nprintf '%s\\n' '{keyscanLine}'\n", () =>
        {
            var exception = Assert.Throws<InvalidOperationException>(() => GitSshTransport.ScanAndVerifyHostKeys(
                "example.test", 22, new SshTrust { Mode = SshHostVerificationMode.Pinned, Fingerprints = [wrongCaseFingerprint] }));

            Assert.Contains("No SSH host key", exception.Message, StringComparison.Ordinal);
        });
    }

    [Fact]
    public void ScanAndVerifyHostKeysAcceptsKeyscanLineWithTrailingComment()
    {
        var key = Convert.ToBase64String(Encoding.UTF8.GetBytes("test SSH host key"));
        var keyscanLine = $"example.test ssh-ed25519 {key} # generated by test";

        WithFakeCommand("ssh-keyscan", $"#!/bin/sh\nprintf '%s\\n' '{keyscanLine}'\n", () =>
        {
            var knownHosts = GitSshTransport.ScanAndVerifyHostKeys(
                "example.test", 22, new SshTrust { Mode = SshHostVerificationMode.Pinned, Fingerprints = [FingerprintFor(key)] });

            Assert.Equal(keyscanLine + "\n", knownHosts);
        });
    }

    [Fact]
    public void ScanAndVerifyHostKeysReportsKeyscanFailure()
    {
        WithFakeCommand("ssh-keyscan", "#!/bin/sh\necho unavailable >&2\nexit 7\n", () =>
        {
            var exception = Assert.Throws<InvalidOperationException>(() => GitSshTransport.ScanAndVerifyHostKeys(
                "example.test", 22, new SshTrust { Mode = SshHostVerificationMode.Pinned, Fingerprints = ["sha256:unused"] }));

            Assert.Contains("exit code 7", exception.Message, StringComparison.Ordinal);
        });
    }

    private static GitAuthentication SshAuthentication() => new()
    {
        Mode = GitAuthenticationMode.Ssh,
        SshPrivateKey = "test private key",
        SshTrust = new SshTrust { Mode = SshHostVerificationMode.None },
    };

    private static string FingerprintFor(string base64Key) =>
        "sha256:" + Convert.ToBase64String(SHA256.HashData(Convert.FromBase64String(base64Key))).TrimEnd('=');

    private static string ChangeBase64LetterCase(string fingerprint)
    {
        var payloadStart = "sha256:".Length;
        for (var index = payloadStart; index < fingerprint.Length; index++)
        {
            if (char.IsUpper(fingerprint[index]))
            {
                return fingerprint[..index] + char.ToLowerInvariant(fingerprint[index]) + fingerprint[(index + 1)..];
            }

            if (char.IsLower(fingerprint[index]))
            {
                return fingerprint[..index] + char.ToUpperInvariant(fingerprint[index]) + fingerprint[(index + 1)..];
            }
        }

        throw new InvalidOperationException("The generated SHA-256 fingerprint contained no letters.");
    }

    private static void RunGitCli(string workingDirectory, params string[] arguments)
    {
        var startInfo = new System.Diagnostics.ProcessStartInfo("git")
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = System.Diagnostics.Process.Start(startInfo)!;
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();
        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException($"git {string.Join(' ', arguments)} failed: {stderr}");
        }
    }

    private static void MakeExecutable(string path)
    {
        if (!OperatingSystem.IsWindows())
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
        }
    }

    private static void WithFakeCommand(string command, string script, Action action)
    {
        lock (PathLock)
        {
            var commandDirectory = TempGitFixtures.CreateTempDirectory();
            var commandPath = Path.Combine(commandDirectory, command);
            File.WriteAllText(commandPath, script);
            MakeExecutable(commandPath);

            var originalPath = Environment.GetEnvironmentVariable("PATH");
            try
            {
                Environment.SetEnvironmentVariable("PATH", commandDirectory + Path.PathSeparator + originalPath);
                action();
            }
            finally
            {
                Environment.SetEnvironmentVariable("PATH", originalPath);
                Directory.Delete(commandDirectory, recursive: true);
            }
        }
    }

    private string Track(string path)
    {
        cleanupPaths.Add(path);
        return path;
    }

    public void Dispose()
    {
        foreach (var path in cleanupPaths)
        {
            if (Directory.Exists(path))
            {
                Directory.Delete(path, recursive: true);
            }
        }
    }
}
